<?php

declare(strict_types=1);

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY bin/cache_routes.php.
 * DO NOT EDIT THIS MANIFEST DIRECTLY.
 *
 * Generated at: 2026-08-29T11:44:49+00:00
 */

use Magma\routing\Route;

return array (
  0 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'GET',
     'uri' => '/forgot-password',
     'handler' => 
    array (
      0 => 'Magma\\controllers\\PasswordResetRequestController',
      1 => 'forgotPassword',
    ),
     'action' => 'forgotPassword',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  1 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'GET',
     'uri' => '/reset-password',
     'handler' => 
    array (
      0 => 'Magma\\controllers\\PasswordResetCompletionController',
      1 => 'resetPasswordForm',
    ),
     'action' => 'resetPasswordForm',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  2 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'GET',
     'uri' => '/',
     'handler' => 
    array (
      0 => 'App\\controllers\\HomeController',
      1 => 'index',
    ),
     'action' => 'index',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  3 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'GET',
     'uri' => '/syllabus',
     'handler' => 
    array (
      0 => 'App\\controllers\\HomeController',
      1 => 'syllabus',
    ),
     'action' => 'syllabus',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  4 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'POST',
     'uri' => '/forgot-password',
     'handler' => 
    array (
      0 => 'Magma\\controllers\\PasswordResetRequestController',
      1 => 'sendResetLink',
    ),
     'action' => 'sendResetLink',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  5 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'POST',
     'uri' => '/reset-password',
     'handler' => 
    array (
      0 => 'Magma\\controllers\\PasswordResetCompletionController',
      1 => 'resetPassword',
    ),
     'action' => 'resetPassword',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  6 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'POST',
     'uri' => '/reviews',
     'handler' => 
    array (
      0 => 'Modules\\Reviews\\controllers\\ReviewController',
      1 => 'submitReview',
    ),
     'action' => 'submitReview',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
);
