<?php

declare(strict_types=1);

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY bin/cache_routes.php.
 * DO NOT EDIT THIS MANIFEST DIRECTLY.
 *
 * Generated at: 2026-08-17T11:03:56+00:00
 */

use Magma\routing\Route;

return array (
  0 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'GET',
     'uri' => '/',
     'handler' => 
    array (
      0 => 'App\\controllers\\HomeController',
      1 => 'index',
    ),
     'action' => 'index',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
  1 => 
  \Magma\routing\Route::__set_state(array(
     'method' => 'POST',
     'uri' => '/reviews',
     'handler' => 
    array (
      0 => 'Modules\\Reviews\\controllers\\ReviewController',
      1 => 'submitReview',
    ),
     'action' => 'submitReview',
     'middleware' => 
    array (
    ),
     'name' => NULL,
     'parameters' => 
    array (
    ),
     'redirectOnFail' => NULL,
     'compiledRegex' => NULL,
  )),
);
