<?php

namespace Magma\models;

use Magma\dto\ReviewDTO;

/**
 * Legacy XML Review Adapter
 *
 * Purpose:
 * - Read and parse legacy XML review data from the filesystem.
 * - Normalize the extracted XML nodes into a consistent array shape that matches SQL models.
 *
 * Why / Why this design:
 * - Implements the Adapter pattern. By normalizing the XML data structure to match the 
 *   SQL data structure, the frontend only needs to understand a single data shape.
 *
 * Teaching notes:
 * - We use `libxml_use_internal_errors` to gracefully catch and log malformed XML issues 
 *   instead of throwing raw PHP warnings. This prevents silent data loss and application 
 *   crashes if a user manually edits the XML file incorrectly.
 */
class XmlReviewRepository
{
    /**
     * Parses the reviews.xml file and returns a collection of ReviewDTO objects.
     * 
     * Execution Flow:
     * 1. Locate and parse the XML file, suppressing warnings for manual error handling.
     * 2. Iterate through the XML nodes and `yield` each normalized ReviewDTO.
     * 
     * Logic behind the logic:
     * - Gracefully catching XML errors prevents application crashes if the file 
     *   is manually edited and corrupted.
     * - Using XMLReader to stream nodes as they are parsed avoids loading the entire resulting dataset 
     *   into memory, maintaining an O(1) memory footprint which is safer for large XML files.
     * 
     * @return iterable<\Magma\dto\ReviewDTO>
     */
    public function getAll(): iterable
    {
        
        $xmlPath = defined('PUBLIC_DIR') ? PUBLIC_DIR . '/xml/reviews.xml' : null;
        
        if ($xmlPath && file_exists($xmlPath)) {
            $reader = new \XMLReader();
            
            // XMLReader::open returns false on failure
            if (!$reader->open($xmlPath)) {
                error_log("Failed to open XML file: " . $xmlPath);
                return;
            }

            // Suppress libxml warnings to catch them manually
            libxml_use_internal_errors(true);

            try {
                while (@$reader->read()) {
                    if ($reader->nodeType == \XMLReader::ELEMENT && $reader->name === 'review') {
                        $reviewData = [];
                        // Using simplexml_load_string on just the outer XML of this single node
                        $nodeXml = @$reader->readOuterXml();
                        if ($nodeXml) {
                            $node = simplexml_load_string($nodeXml);
                            if ($node !== false) {
                                foreach ($node->children() as $childName => $childValue) {
                                    $reviewData[$childName] = (string)$childValue;
                                }
                                $reviewData['rating'] = (int)($reviewData['rating'] ?? 5);
                                yield $this->normalize($reviewData);
                            } else {
                                $this->logXmlErrors($xmlPath);
                            }
                        }
                    }
                    // Clear any buffered libxml warnings generated by this node to prevent memory leak
                    libxml_clear_errors();
                }
                
                // Check if there were reading errors outside of node parsing
                $this->logXmlErrors($xmlPath);
            } finally {
                libxml_clear_errors();
                $reader->close();
            }
        } else {
            error_log("XML Review file not found at expected path: " . ($xmlPath ?: 'Unknown'));
        }

    }

    /**
     * Helper to log libxml errors and clear the buffer.
     */
    private function logXmlErrors(string $xmlPath): void
    {
        $errors = libxml_get_errors();
        foreach ($errors as $error) {
            error_log(sprintf(
                "XML Parsing Error in %s: %s on line %d",
                $xmlPath,
                trim($error->message),
                $error->line
            ));
        }
        libxml_clear_errors();    }

    /**
     * Standardizes review keys and maps them into a DTO.
     * 
     * Execution Flow:
     * 1. Safely extract author, comment, and rating using fallback keys.
     * 2. Instantiate and return a ReviewDTO.
     * 
     * Logic behind the logic:
     * - Since XML nodes often have inconsistent naming compared to the database, 
     *   this private utility standardizes the shape before it leaves the repository.
     */
    private function normalize(array $data): ReviewDTO
    {
        $comment = $data['comment'] ?? $data['text'] ?? $data['review_text'] ?? '';
        $comment = trim((string)$comment) ?: 'No comment provided';

        $author = $data['author'] ?? $data['name'] ?? $data['reviewer_name'] ?? '';
        $author = trim((string)$author) ?: 'Anonymous';

        return new ReviewDTO(
            author: $author,
            comment: $comment,
            rating: (int)($data['rating'] ?? 5)
        );
    }
}