<?php

declare(strict_types=1);

namespace Magma\assets;

use Magma\config\Config;

/**
 * Title: Deterministic Asset Version Manager
 *
 * Purpose:
 * - Provides centralized, deterministic cache-busting for static CSS, JavaScript, and media assets.
 * - Replaces unstable runtime timestamps (`time()`) with content hashes or application release tags (`APP_ASSET_VERSION`).
 *
 * Why / Why this design:
 * - HTTP Cache Optimization: Dynamic query strings (like `?v=time()`) force browsers to re-download
 *   all stylesheets and scripts on every page load, ruining performance and wasting bandwidth.
 *   Deterministic versioning allows immutable long-term HTTP caching (`Cache-Control: max-age=31536000, immutable`).
 * - In-Memory Hash Caching: Calculating `md5_file()` on every request degrades I/O performance.
 *   Hashes are computed once per distinct asset and cached in memory.
 * - Manifest Support: Seamlessly reads JSON manifests generated by Vite, Webpack, or custom asset build pipelines.
 *
 * Teaching notes:
 * - Call `ViewHelper::asset('/css/app.css')` inside templates rather than hardcoding static paths.
 */
class AssetVersionManager
{
    /** @var self|null Singleton instance. */
    private static ?self $instance = null;

    /** @var string Public document root directory. */
    private string $publicDir;

    /** @var string|null Global application release version tag. */
    private ?string $releaseVersion = null;

    /** @var array<string, string|array<string, mixed>> Parsed build manifest mappings. */
    private array $manifest = [];

    /** @var array<string, string> In-memory cache of resolved asset URLs. */
    private array $urlCache = [];

    /**
     * Initializes the asset version manager.
     *
     * @param string|null $publicDir Absolute path to public web directory (defaults to PUBLIC_DIR constant).
     * @param string|null $releaseVersion Fixed release version string (or read from environment/Config).
     * @param string|null $manifestPath Optional path to JSON manifest.
     */
    public function __construct(
        ?string $publicDir = null,
        ?string $releaseVersion = null,
        ?string $manifestPath = null
    ) {
        $this->publicDir = $publicDir ?? (defined('PUBLIC_DIR') ? PUBLIC_DIR : dirname(__DIR__, 2) . '/www');
        
        if ($releaseVersion !== null) {
            $this->releaseVersion = $releaseVersion;
        } elseif (class_exists(Config::class)) {
            $cfgVersion = Config::get('APP_ASSET_VERSION', Config::get('APP_VERSION', null));
            if (is_scalar($cfgVersion)) {
                $this->releaseVersion = (string)$cfgVersion;
            }
        }

        if ($manifestPath !== null) {
            $this->setManifestPath($manifestPath);
        }
    }

    /**
     * Retrieves the singleton instance.
     *
     * @return self
     */
    public static function getInstance(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Sets the singleton instance.
     *
     * @param self $instance
     * @return void
     */
    public static function setInstance(self $instance): void
    {
        self::$instance = $instance;
    }

    /**
     * Sets the public document root directory.
     *
     * @param string $publicDir
     * @return void
     */
    public function setBasePublicDir(string $publicDir): void
    {
        $this->publicDir = rtrim($publicDir, '/\\');
        $this->urlCache = [];
    }

    /**
     * Sets a global application release version tag.
     *
     * @param string $version
     * @return void
     */
    public function setReleaseVersion(string $version): void
    {
        $this->releaseVersion = $version;
        $this->urlCache = [];
    }

    /**
     * Sets the path to a JSON build manifest file and loads its mappings.
     *
     * @param string $manifestPath
     * @return void
     */
    public function setManifestPath(string $manifestPath): void
    {
        $this->manifest = [];

        if (file_exists($manifestPath)) {
            $content = file_get_contents($manifestPath);
            if ($content !== false) {
                $decoded = json_decode($content, true);
                if (is_array($decoded)) {
                    $typedManifest = [];
                    foreach ($decoded as $key => $value) {
                        if (is_string($key) && (is_string($value) || is_array($value))) {
                            $typedManifest[$key] = $value;
                        }
                    }
                    $this->manifest = $typedManifest;
                }
            }
        }

        $this->urlCache = [];
    }

    /**
     * Resolves a public static asset path into a cache-busted URL.
     *
     * Execution Flow:
     * 1. Check in-memory URL cache.
     * 2. Check JSON build manifest for compiled hash filename.
     * 3. If global release version is set, append `?v=<version>`.
     * 4. Otherwise, compute deterministic 8-character MD5 content hash or filemtime from disk.
     * 5. Cache and return the resolved URL.
     *
     * @param string $path Relative asset path (e.g. '/css/app.css' or 'js/app.js').
     * @return string Cache-busted asset URL.
     */
    public function getAssetUrl(string $path): string
    {
        $normalizedPath = '/' . ltrim($path, '/');

        if (isset($this->urlCache[$normalizedPath])) {
            return $this->urlCache[$normalizedPath];
        }

        // 1. Manifest lookup
        $manifestKey = ltrim($normalizedPath, '/');
        if (isset($this->manifest[$manifestKey])) {
            $hashed = $this->manifest[$manifestKey];
            $fileStr = is_array($hashed) ? ($hashed['file'] ?? '') : $hashed;
            $url = '/' . ltrim(is_scalar($fileStr) ? (string)$fileStr : '', '/');
            $this->urlCache[$normalizedPath] = $url;
            return $url;
        }

        // 2. Global release version
        if (!empty($this->releaseVersion)) {
            $url = $normalizedPath . '?v=' . urlencode($this->releaseVersion);
            $this->urlCache[$normalizedPath] = $url;
            return $url;
        }

        // 3. Local file hash
        $fullPath = $this->publicDir . $normalizedPath;
        if (file_exists($fullPath)) {
            $hash = substr((string) md5_file($fullPath), 0, 8);
            $url = $normalizedPath . '?v=' . $hash;
        } else {
            // Fallback if file does not exist on disk
            $url = $normalizedPath;
        }

        $this->urlCache[$normalizedPath] = $url;
        return $url;
    }

    /**
     * Retrieves the version hash or tag for a specific asset.
     *
     * @param string $path Relative asset path.
     * @return string Version string.
     */
    public function getVersion(string $path): string
    {
        if (!empty($this->releaseVersion)) {
            return $this->releaseVersion;
        }

        $normalizedPath = '/' . ltrim($path, '/');
        $fullPath = $this->publicDir . $normalizedPath;

        if (file_exists($fullPath)) {
            return substr((string) md5_file($fullPath), 0, 8);
        }

        return '1.0.0';
    }

    /**
     * Clears all in-memory URL caches.
     *
     * @return void
     */
    public function clearCache(): void
    {
        $this->urlCache = [];
    }
}
